#!/bin/bash
bold=$(tput bold)
normal=$(tput sgr0)
version="${bold}Version${normal} 12.0 by snowfag Yuki@lolicon.eu"
if ! hash chan-dl 2>/dev/null
  then
    echo "To run this script it must be in your path."
    exit 1
fi
case "$1" in
  -r)
      if ! [ -z "$3" ]
        then
          if [ $3 == threadwatcher ]
            then
              threadwatcher="1"
            else
              threadwatcher="0"
          fi
        else
          threadwatcher="0"
      fi
      if [ -z "$2" ]
        then
          echo "No url entered."
          exit 1
        else
          if ! [ $(echo "$2" | grep -q "^http://"; echo $?) -eq 0 ]
            then
              echo "Incorrect url format! Be sure your url begins with http://"
              exit 1
          fi
          site=$(echo "$2"| awk -F\/ '{print $3}')
      fi
      escaped=$(echo "$2" | sed 's/[\/]/\\\//g')
      if [ ${site} == "boards.4chan.org" ]
        then
          domain="i.4cdn.org"
          thread=$(echo "$2" | awk -F\/ '{ print $4$6 }')
        else
          if [ ${site} == 8ch.net ]
            then
              domain="media.8ch.net"
              thread=$(echo "$2" | awk -F\/ '{ gsub(/.html$/,""); print $4 "-" $6 }')
            else
              echo "Unsupported Site."
              exit 1
          fi
      fi
      if [ -d "${PWD}/${thread}" ]
        then
          cd ${PWD}/${thread}
        else
            mkdir ${PWD}/${thread}
              cd ${PWD}/${thread}
      fi
      ERRORS=0
      while [ ${ERRORS} -lt 6 ]
      do
            WGETO=$(wget -H --no-directories -D ${domain} -r -l 1 -U Mozilla -A jpeg,jpg,png,gif,webm -R '*s.*' -nc -e robots=off ${2} 2>&1)
            ECODE=$(echo $?)
            DLCOUNT=$(echo "${WGETO}" | awk '/Downloaded/ {files=$2} END { print files }')
            if ! [ -z "${DLCOUNT}" ]
              then
                if ! [ ${DLCOUNT} -eq 1 ]
                  then
                    echo "Downloaded Files: ${DLCOUNT}"
                fi
            fi
            if ! [ ${ECODE} -eq 0 ]
              then
                let ERRORS=ERRORS+1
              else
                if [ ${ERRORS} -gt 0 ]
                  then
                    ERRORS=0
                fi
            fi
            sleep 600
      done
      if [ ${ERRORS} -eq 6 ]
        then
          if [ ${threadwatcher} -eq 1 ]
            then
              sed -i "/^${escaped}$/d" "$HOME/.threadwatchlist"
          fi
            echo "Thread died."
            exit 1
      fi
  ;;
  -a)
      echo "$2" >> "$HOME/.threadwatchlist"
      ( chan-dl -r "$2" threadwatcher & )
  ;;
  -d)
      escaped=$(echo "$2" | sed 's/[\/]/\\\//g')
      sed -i "/^${escaped}$/d" "$HOME/.threadwatchlist"
  ;;
  -s)
      for i in $(cat "$HOME/.threadwatchlist" )
      do
        ( chan-dl -r "$i" threadwatcher & )
      done
  ;;
  -v)
      echo -e "${version}"
      exit 0
  ;;
  -h)
      echo -e "${version}\n\n\t${bold}-r${normal} Run download function without adding the url to the thread watch list\n\n\t${bold}-a${normal} Adds url to thread watch list and starts chan-dl on url\n\n\t${bold}-d${normal} Removes url from thread watch list\n\n\t${bold}-s${normal} Starts chan-dl on all the urls contained within the thread watch list\n\n\t${bold}-v${normal} Prints version info\n\n\t${bold}-h${normal} Prints this help info"
  ;;
  *)
      echo "Invalid option. Try -h"
      exit 1
esac
exit 0
