#!/bin/bash
#Name chan-dl.sh
#Version - v11.2
#Author - snowfag
#Example Usage - /path/to/script host.dix/url
if ! [ -z "$2" ]
  then
    if [ $2 == wrapper ]
      then
        wrapper="1"
    fi
  else
    wrapper="0"
fi
if [ -z "$1" ]
  then
    echo "No url entered."
    exit 1
  else
    site=$(echo "$1"| awk -F\/ '{print $3}')
fi
escaped=$(echo "$1" | sed 's/[\/]/\\\//g')
ECODE=0
if [ ${site} == "boards.4chan.org" ]
  then
    domain="i.4cdn.org"
    thread=$(echo "$1" | awk -F\/ '{ print $4$6 }')
  else
    if [ ${site} == 8ch.net ]
      then
        domain="media.8ch.net"
        thread=$(echo "$1" | awk -F\/ '{ gsub(/.html$/,""); print $4 "-" $6 }')
      else
        echo "Unsupported Site."
        exit 1
    fi
fi
if [ -d "${PWD}/${thread}" ]
  then
    cd ${PWD}/${thread}
  else
      mkdir ${PWD}/${thread}
        cd ${PWD}/${thread}
fi
while [ ${ECODE} -eq 0 ]
do
      WGETO=$(wget -H --no-directories -D ${domain} -r -l 1 -U Mozilla -A jpeg,jpg,png,gif,webm -R '*s.*' -nc -e robots=off ${1} 2>&1)
      ECODE=$(echo $?)
      DLCOUNT=$(echo "${WGETO}" | awk '/Downloaded/ {files=$2} END { print files }')
      if ! [ -z "${DLCOUNT}" ]
        then
          if ! [ ${DLCOUNT} -eq 1 ]
            then
              echo "Downloaded Files: ${DLCOUNT}"
          fi
      fi
      if ! [ ${ECODE} -eq 0 ]
        then
          sleep 600
          WGETO=$(wget -H --no-directories -D ${domain} -r -l 1 -U Mozilla -A jpeg,jpg,png,gif,webm -R '*s.*' -nc -e robots=off ${1} 2>&1)
          ECODE=$(echo $?)
          DLCOUNT=$(echo "${WGETO}" | awk '/Downloaded/ {files=$2} END { print files }')
          if ! [ -z "${DLCOUNT}" ]
            then
              if ! [ ${DLCOUNT} -eq 1 ]
                then
                  echo "Downloaded Files: ${DLCOUNT}"
              fi
          fi
          if ! [ ${ECODE} -eq 0 ]
            then
              if [ ${wrapper} -eq 1 ]
                then
                  sed -i "/^${escaped}$/d" "$HOME/.threadwatchlist"
              fi
                echo "Thread died."
                exit 1
          fi
      fi
          sleep 600
done
exit 0
